---
- name: Copy the EPEL repository definition
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install Java
  yum: name=java state=latest

- name: Install Elasticsearch
  yum: name=elasticsearch state=present

- name: Install Config Template
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml

- name: Start Elasticsearch
  service: name=elasticsearch state=started  

- name: Set to autostart
  shell: chkconfig --add elasticsearch

- name: Allow incoming ES cluster connections to other nodes in the cluster
  iptables: chain=INPUT
            action=insert
            source={{ item }}/32
            protocol=tcp 
            match=tcp 
            state=present
            ctstate=NEW
            destination_port=9300
            jump=ACCEPT
  with_items: "{{ iplist }}"
