---
- name: Copy the EPEL repository definition
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install Java
  yum: name=java state=latest

- name: Install Elasticsearch
  yum: name=elasticsearch state=present

#- name: Install Config
#  copy: src=00-input.conf dest=/etc/logstash/conf.d/00-input.conf
#  notify: restart logstash

- name: Start Elasticsearch
  service: name=elasticsearch state=started  

- name: Set to autostart
  shell: chkconfig --add elasticsearch

#- name: Allow incoming connections
#  iptables: chain=INPUT
#            action=insert
#            source=0.0.0.0/0
#            protocol=tcp 
#            match=tcp 
#            state=present 
#            ctstate=NEW 
#            destination_port=3000
#            jump=ACCEPT 
 

